# Generated by Django 5.2.7 on 2026-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("scam", "Scam"),
                    ("abuse", "Abuse"),
                    ("wrong_info", "Wrong information"),
                    ("fake_landlord", "Fake landlord"),
                    ("fake_listing", "Fake listing"),
                    ("deposit_scam", "Deposit scam"),
                    ("impersonation", "Someone impersonating Rooms4You"),
                    ("suspicious_payment", "Suspicious payment request"),
                    ("tenant_unreachable", "Tenant unreachable / went AWOL"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
