# Generated by Django 6.0 on 2026-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("now", "Available now"),
                    ("from", "Occupied (available from)"),
                    ("mixed", "Some available now"),
                ],
                default="now",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="available_units",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="full_address",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="postal_code",
            field=models.CharField(default="Unknown address", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="total_units",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
