# Generated by Django 6.0 on 2026-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_change_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
