# Generated by Django 6.0 on 2026-05-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomimage",
            options={"ordering": ["created_at"]},
        ),
    ]
