# Generated by Django 6.0 on 2026-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
    ]
