# Generated by Django 6.0 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_room_availability_status_room_available_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomstat",
            name="stat_type",
            field=models.CharField(max_length=20),
        ),
    ]
