# Generated by Django 6.0 on 2026-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_roomimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified_landlord",
            field=models.BooleanField(
                default=False, help_text="Admin verified landlord badge"
            ),
        ),
    ]
