# Generated by Django 6.0 on 2026-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_profile_is_verified_landlord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("driver", "Driver"),
                ],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
