# Generated by Django 6.0 on 2026-02-17 19:02

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_roomstat_stat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
