# Generated by Django 6.0 on 2026-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="city",
            field=models.CharField(default="None", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="province",
            field=models.CharField(default="Gauteng", max_length=120),
        ),
        migrations.AddField(
            model_name="room",
            name="suburb",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="town",
            field=models.CharField(default="default", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("landlord", "Landlord")],
                default="tenant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Single Room", "Single Room"),
                    ("Shared Room", "Shared Room"),
                    ("Bachelor", "Bachelor"),
                    ("Ensuite", "Ensuite"),
                    ("Student Accommodation", "Student Accommodation"),
                    ("Backroom", "Backroom"),
                    ("Cottage", "Cottage"),
                    ("Apartment", "Apartment"),
                ],
                max_length=30,
            ),
        ),
    ]
