# Generated by Django 6.0 on 2026-01-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="contacted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="moved_in",
        ),
    ]
