# Generated by Django 6.0 on 2026-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_room_city_room_province_room_suburb_room_town_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gps_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gps_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gps_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gps_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gps_source",
            field=models.CharField(
                choices=[
                    ("self", "Self reported"),
                    ("browser", "Browser GPS"),
                    ("admin", "Admin verified"),
                ],
                default="self",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roomstat",
            name="address_confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="roomstat",
            name="gps_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomstat",
            name="gps_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomstat",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
    ]
