# Generated by Django 6.0 on 2026-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_rename_contacted_at_contact_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
