# Generated by Django 6.0 on 2026-03-03 13:09

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0005_profile_alt_no_profile_cell_no_profile_home_address_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                django.db.models.functions.text.Lower("location"),
                models.F("room_type"),
                models.F("price"),
                models.F("owner"),
                name="uniq_room_owner_title_location_type_price",
            ),
        ),
    ]
