# Generated by Django 6.0 on 2026-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_room_uniq_room_owner_title_location_type_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
