# Generated by Django 6.0 on 2026-05-19 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_profile_gps_accuracy_profile_gps_captured_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_available"], name="listings_ro_is_avai_83c669_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["location"], name="listings_ro_locatio_5eaac8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["price"], name="listings_ro_price_e92d5d_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["created_at"], name="listings_ro_created_ec1287_idx"
            ),
        ),
    ]
