# Generated by Django 6.0 on 2026-05-19 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_room_listings_ro_is_avai_83c669_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(fields=["user"], name="listings_fa_user_id_dec971_idx"),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(fields=["room"], name="listings_fa_room_id_e2e226_idx"),
        ),
        migrations.AddIndex(
            model_name="roomstat",
            index=models.Index(fields=["room"], name="listings_ro_room_id_319b25_idx"),
        ),
        migrations.AddIndex(
            model_name="roomstat",
            index=models.Index(
                fields=["stat_type"], name="listings_ro_stat_ty_a94000_idx"
            ),
        ),
    ]
