# Generated by Django 6.0 on 2026-01-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_roomstat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomstat",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.room"
            ),
        ),
        migrations.AlterField(
            model_name="roomstat",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("contact", "Contact"),
                    ("success", "Success"),
                ],
                max_length=20,
            ),
        ),
    ]
