# Generated by Django 6.0 on 2026-05-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_favorite_listings_fa_user_id_dec971_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="EmailVerification",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
