# Generated by Django 6.0 on 2026-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_roomimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomstat",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("contact_phone", "Phone"),
                    ("contact_whatsapp", "WhatsApp"),
                    ("contact_email", "Email"),
                    ("success", "Success"),
                ],
                max_length=20,
            ),
        ),
    ]
