# Generated by Django 6.0 on 2026-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_alter_roomstat_stat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="room",
            name="contact_whatsapp",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
