# Generated by Django 6.0 on 2026-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_alter_contact_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
