# Generated by Django 6.0 on 2026-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_profile_privacy_accepted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("landlord", "Landlord")],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
