# Generated by Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hits",
            field=models.PositiveIntegerField(default=0, db_index=True),
        ),
    ]
