# Generated by Django 5.2.7 on 2026-08-13 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_add_roomimage_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roomstat',
            name='listings_ro_room_id_319b25_idx',
        ),
        migrations.AddIndex(
            model_name='roomstat',
            index=models.Index(fields=['room', 'stat_type'], name='roomstat_room_type_idx'),
        ),
    ]
