# Generated by Django 5.2.7 on 2026-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_add_room_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ('order', 'created_at')},
        ),
    ]
