# Generated by Django 5.2.7 on 2026-08-31 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_alter_message_options_alter_roomimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="last_confirmed_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="last_nudge_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
