# Generated by Django 5.2.7 on 2026-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0021_room_last_confirmed_at_room_last_nudge_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avg_response_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="response_rate_percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="responses_measured",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
