# Generated by Django 5.2.7 on 2026-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0022_profile_avg_response_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="no_listing_nudge_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
