# Generated by Django 5.2.7 on 2026-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0023_profile_no_listing_nudge_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
