# Generated by Django 5.2.7 on 2026-07-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="placement",
            new_name="placements__status_050fcb_idx",
            old_name="placements_status_idx",
        ),
        migrations.RenameIndex(
            model_name="placement",
            new_name="placements__landlor_29d3d9_idx",
            old_name="placements_landlord_status_idx",
        ),
        migrations.RenameIndex(
            model_name="placement",
            new_name="placements__tenant__7bd4c7_idx",
            old_name="placements_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="placement",
            new_name="placements__move_in_650e52_idx",
            old_name="placements_move_in_date_idx",
        ),
    ]
