# Generated by Django 5.2.7 on 2026-08-13 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_roomstat_composite_index'),
        ('placements', '0002_rename_placements_status_idx_placements__status_050fcb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements_as_landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placement',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='listings.room'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
