# Generated by Django 5.2.7 on 2026-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_protect_financial_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementstatushistory',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Placement status history'},
        ),
    ]
