# Generated by Django 5.2.7 on 2026-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0004_alter_placementstatushistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="stall_nudge_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placement",
            name="tenant_flagged_unreachable_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
