# Generated by Django 6.0 on 2026-05-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bakkiedriver",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="bakkiedriver",
            name="whatsapp_number",
        ),
        migrations.RemoveField(
            model_name="panicalert",
            name="message",
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardiansession",
            name="latest_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardiansession",
            name="latest_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardiansession",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("ended", "Ended"), ("panic", "Panic")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bakkiedriver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bakkie_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bakkiedriver",
            name="vehicle_registration",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="bakkiedriver",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("small", "Small Bakkie"),
                    ("medium", "Medium Truck"),
                    ("large", "Large Truck"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="guardiansession",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="panicalert",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="services.guardiansession",
            ),
        ),
        migrations.CreateModel(
            name="GuardianLocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="services.guardiansession",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GuardianLocation",
        ),
    ]
