# Generated by Django 6.0 on 2026-05-11 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_phone_bakkiedriver_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="licence_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="driver_license"
            ),
        ),
    ]
