# Generated by Django 6.0 on 2026-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_bakkiedriver_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="address",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="province",
            field=models.CharField(default="unknown", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
