# Generated by Django 6.0 on 2026-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_bakkiedriver_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
