# Generated by Django 6.0 on 2026-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_bakkiedriver_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="completed_jobs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),  # pyright: ignore[reportArgumentType]
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),  # pyright: ignore[reportArgumentType]
        ),
    ]
