# Generated by Django 6.0 on 2026-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_remove_bakkiedriver_is_available_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverBooking",
        ),
    ]
