# Generated by Django 6.0 on 2026-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_delete_driverbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
