# Generated by Django 6.0 on 2026-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_bakkiedriver_privacy_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakkiedriver",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bakkiedriver",
            name="verification_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
