# Generated by Django 6.0 on 2026-04-14 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Payment"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("upgraded_to", models.CharField(blank=True, max_length=20, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter4You"),
                            ("bronze", "Bronze4You"),
                            ("silver", "Silver4You"),
                            ("gold", "Gold4You"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_trial", models.BooleanField(default=True)),
                (
                    "trial_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("payment_requested", models.BooleanField(default=False)),
                ("payment_requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
