# Generated by Django 6.0 on 2026-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="membership_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
