# Generated by Django 6.0 on 2026-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_membership_membership_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="requested_tier",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
