# Generated by Django 6.0 on 2026-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_requested_tier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="upgraded_to",
        ),
        migrations.AddField(
            model_name="membership",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payments/"),
        ),
    ]
