# Generated by Django 6.0 on 2026-05-04 05:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_membership_upgraded_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="payment_proof",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="payment_proof"
            ),
        ),
    ]
