# Generated by Django 6.0 on 2026-05-04 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_membership_payment_proof"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="payment_proof",
        ),
        migrations.AddField(
            model_name="membership",
            name="proof_of_payment",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
