# Generated by Django 5.2.7 on 2026-08-14 09:52

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=120)),
                ('town', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(default='Gauteng', max_length=120)),
                ('full_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='10:00')),
                ('house_rules', models.TextField(blank=True, default='')),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_aircon', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesthouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_guests', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=12)),
                ('message', models.TextField(blank=True, default='')),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='stays.guesthouse')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='stays.guesthouse')),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stays.guesthouse')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guesthouse',
            index=models.Index(fields=['is_active'], name='stays_guest_is_acti_611e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='guesthouse',
            index=models.Index(fields=['location'], name='stays_guest_locatio_0a1e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='guesthouse',
            index=models.Index(fields=['price_per_night'], name='stays_guest_price_p_11df5d_idx'),
        ),
        migrations.AddIndex(
            model_name='guesthouse',
            index=models.Index(fields=['created_at'], name='stays_guest_created_01b880_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guesthouse', 'status'], name='stays_booki_guestho_f213e9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest'], name='stays_booki_guest_i_0ab062_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='stays_booki_check_i_d4861c_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeddate',
            index=models.Index(fields=['guesthouse', 'start_date', 'end_date'], name='stays_block_guestho_381181_idx'),
        ),
    ]