# Generated by Django 5.2.7 on 2026-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_add_booking_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinginvoice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='guesthouseimage',
            options={'ordering': ('order', 'created_at')},
        ),
    ]
